# Generated by Django 2.2 on 2019-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('monitor', 'Мониторы'), ('hdd', 'Жесткие диски'), ('keyboard', 'Клавиатуры'), ('mouse', 'Мышки'), ('cpu', 'Центральные процессоры')], default='other', max_length=50, verbose_name='Категория')),
                ('remain', models.PositiveIntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
        ),
    ]
